#!/bin/bash
printf "Content-type: text/html\n\n"

function getmac {
   re=$(ip -6 neig show | grep $1 | awk '{print $5}')
   echo $re
}
function getsignal {
  re=$(iw $1 station dump | grep -A 12 "$2"  | grep signal\ avg | awk '{print $3}')
  echo $re
}
function getifmac {
    echo $(ifconfig  $1 | head -n 1 | awk '{print tolower($5)}')
}

start=0
current='';
QUERY_STRING=$(echo "$QUERY_STRING" | tr -dc '[:digit:]\.')

if [ ! -z "$QUERY_STRING" ]; then
    if [ -z "$(which curl)" ]; then
        wget -qO- http://$QUERY_STRING/cgi-bin/vis
    else
        curl -q http://$QUERY_STRING/cgi-bin/vis
    fi
exit
fi


echo "{"

echo dump | nc :: 999 -w 1 | while read p
do
    index=$((index+1))
    parm=$(echo $p | cut -d" " -f 1 )
    parm2=$(echo $p | cut -d" " -f 2)
    case $parm in
        ok)
        ;;
        BABEL|version|host|my-id)
            echo "\"$parm\" : \"$parm2\","
        ;;
        *)
            if [ "$start" == '0' ]; then
                echo "\"noop\" : {"
                start='1'
            fi

            if [[ "$current" != "$parm2" ]]; then 
                echo " \"noop\" : \"\" }, \"$parm2\" : {"
                current="$parm2"
            fi

            case $parm2 in
                interface)
                    iface="$(echo $p | cut -d" " -f 3)"
                    ip="$(echo $p | cut -d" " -f 7)"
                    mac=$(getifmac $iface)
                    echo "\"$iface\" : { \"ip\":\"$ip\",\"mac\":\"$mac\", \"all\": \"$p\"},"
                ;;
                neighbour)
                    ip=$(echo $p | cut -d" " -f 5)
                    mac=$(getmac $ip)
                    ifname=$(echo $p | cut -d" " -f 7)                                                                                                                                                             
                    signal=$(getsignal $ifname $mac)                                                                                                                                                               
                    echo "\"$(echo $p | cut -d" " -f 5)\"  : { \"ip\": \"$ip\", \"if\" : \"$ifname\", \"all\" :\"$p\", \"mac\" : \"$mac\", \"signal\":\"$signal\" }, ";                  ;;
                route)
                    routeid="$(echo $p | cut -d" " -f 3)"
                    nodeid="$(echo $p | cut -d" " -f 11)"
                        echo  "\"$routeid\" : { \"nodeid\":\"$nodeid\", \"installed\" : \"$(echo $p | cut -d" " -f 9)\", \"target\" : \"$(echo $p | cut -d" " -f 5)\" ,\"ip\":\"$(echo $p | cut -d" " -f 17)\", \"all\" : \"$p\" }, ";
                ;;
                xroute)
                      route=$(echo $p | cut -d" " -f 5)
                      echo "\"$parm2$index\" : { \"route\": \"$route\" , \"all\" : \"$p\" }, ";
                ;;
                *)
                    echo "\"$parm2$index\" : { \"all\" : \"$p\" }, ";
                ;;
            esac
        ;;
    esac
done
echo " \"noop\" : \"\" }"
echo "}"

